FROM debian:bullseye

RUN apt-get update \
    && apt-get install --yes --no-install-recommends \
        openssh-server \
    && rm -rfv /var/lib/apt/lists/

# Deny root shell access
RUN chsh --shell /bin/false root

# Prevent error: "Missing privilege separation directory: /run/sshd"
RUN mkdir -v /run/sshd

# Create config and secret directory
RUN mkdir /config

COPY ./sshd_config /etc/ssh/sshd_config
COPY ./entrypoint.sh /entrypoint.sh

EXPOSE 22
VOLUME ["/config"]
WORKDIR /

CMD /entrypoint.sh
